# Generated by Django 3.1.2 on 2020-10-10 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.IntegerField()),
                ('nationality', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=64)),
                ('issue_date', models.DateField()),
                ('issue_place', models.CharField(max_length=64)),
                ('expiry_date', models.DateField()),
                ('authority', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('gender', models.IntegerField()),
                ('clan', models.CharField(max_length=8)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
