# Generated by Django 3.1.2 on 2021-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210121_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancel_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Canceled'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='change_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Changed'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused'), (5, 'Completed')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='normal_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Booked'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused'), (5, 'Completed')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket_history',
            name='cancel_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Canceled'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket_history',
            name='change_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Changed'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused'), (5, 'Completed')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket_history',
            name='normal_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Booked'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused'), (5, 'Completed')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket_history',
            name='type_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
