# Generated by Django 3.1.2 on 2021-01-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210114_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='ticket_history',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_confirm',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_history',
            name='is_confirm',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
