# Generated by Django 3.1.2 on 2021-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210228_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cancel_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Canceled'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused'), (5, 'Completed')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_history',
            name='cancel_status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (1, 'Canceled'), (2, 'Watting'), (3, 'Confirmed'), (4, 'Refused'), (5, 'Completed')], default=0, null=True),
        ),
    ]
