# Generated by Django 3.1.2 on 2021-01-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20210120_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='itinerary_history',
            name='ticket',
        ),
    ]
