# Generated by Django 3.1.2 on 2021-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ios', 'Ios'), ('Android', 'Android')], default='Android', max_length=16)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/app/')),
                ('redirect', models.URLField(blank=True, null=True)),
                ('enable_redirect', models.BooleanField(default=False)),
            ],
        ),
    ]
